language: python


python:
    - 3.5
    - nightly


before_install: pip install anglerfish --quiet


before_script: rm --recursive --force --verbose *.py[cod]


script:
    - wget --no-check-certificate https://code.jquery.com/jquery-git2.js
    - chmod +x $TRAVIS_BUILD_DIR/css-html-js-minify.py
    - $TRAVIS_BUILD_DIR/css-html-js-minify.py --prefix temp_ --timestamp --hash --beep --zipy $TRAVIS_BUILD_DIR/jquery-git2.js
    - wget --no-check-certificate https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.css
    - $TRAVIS_BUILD_DIR/css-html-js-minify.py --prefix temp_ --timestamp --wrap --hash --beep $TRAVIS_BUILD_DIR/bootstrap.css
    - python3 -m unittest $TRAVIS_BUILD_DIR/tests/test_*
    - pip install --upgrade --no-compile css-html-js-minify


notifications:
    email:
        recipients: juancarlospaco@gmail.com
        on_success: change
        on_failure: always


cache:
  apt: true
  pip: true
